name: Substantials
version: 1.0.0
main: au.id.jrose.substantials.Main
api-version: 1.18
commands:
  home:
    description: Teleport to your home.
    usage: "§c/<command> [name]"
  sethome:
    description: Sets the location of your home.
    usage: "§c/<command> [name]"
  delhome:
    description: Deletes a saved home.
    usage: "§c/<command> [name]"
  nickname:
    aliases:
      - nick
    description: Sets your server nickname (displayed to other players).
    usage: "§c/<command> [clear/name]"
  homes:
    description: List all homes.
    usage: "§c/<command>"